[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "test/ERC1271/ERC712.json" },
    { access = "read-write", path = "/tmp/ERC712-test.json" },
]

remappings = [
    "keyspace-v2/=lib/keyspace-v2/contracts/src/",
]

[profile.deploy]
optimizer = true
optimizer_runs = 999999

[fmt]
sort_imports = true
wrap_comments = true
